[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["cd backend && python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && python app.py"
