services:
  - type: web
    name: ai-interview-assistant
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
